# Generated by Django 4.2 on 2023-07-12 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0021_alter_color_quantity_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='prod_and_amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.color_quantity')),
            ],
        ),
        migrations.CreateModel(
            name='yatra_bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Accepted', max_length=20)),
                ('payment_status', models.CharField(choices=[('Completed', 'Completed'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled'), ('Waiting', 'Waiting')], default='Waiting', max_length=20)),
                ('yatra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.travel')),
                ('yatra_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.app_users')),
            ],
        ),
        migrations.CreateModel(
            name='product_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20, unique=True)),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(null=True)),
                ('payment_status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled'), ('Waiting', 'Waiting')], default='Waiting', max_length=20)),
                ('done_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.app_users')),
                ('products_associated', models.ManyToManyField(to='customers.prod_and_amount')),
            ],
        ),
        migrations.CreateModel(
            name='product_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('payment_status', models.CharField(choices=[('Completed', 'Completed'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled'), ('Waiting', 'Waiting')], default='Completed', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.app_users')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.color_quantity')),
            ],
        ),
        migrations.CreateModel(
            name='gift_requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Waiting', 'Waiting')], default='Waiting', max_length=20)),
                ('product_associated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.color_quantity')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.app_users')),
            ],
        ),
        migrations.CreateModel(
            name='ceremony_bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_scheduled', models.DateTimeField(null=True)),
                ('payment_status', models.CharField(choices=[('Completed', 'Completed'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled'), ('Waiting', 'Waiting')], default='Waiting', max_length=20)),
                ('ceremony_booked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.ceremony')),
                ('priest_selected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.priests')),
                ('user_associated', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.app_users')),
            ],
        ),
    ]
