# Generated by Django 4.2 on 2023-07-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod_and_amount',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
