# Generated by Django 4.2 on 2023-07-20 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_alter_color_quantity_product'),
        ('customers', '0002_prod_and_amount_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_orders',
            name='address',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.saved_address'),
        ),
    ]
