# Generated by Django 4.0.3 on 2022-07-11 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_users',
            name='alternate_phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='app_users',
            name='anniversary',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='app_users',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='app_users',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='app_users',
            name='permanent_Address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.permanent_address'),
        ),
    ]
