# Generated by Django 4.0.3 on 2022-07-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_app_users_alternate_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_users',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
