# Generated by Django 4.0.3 on 2022-07-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_app_users_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_users',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
