# Generated by Django 4.0.3 on 2022-08-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_color_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='color_quantity',
            name='photo',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
