# Generated by Django 4.0.3 on 2022-08-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_color_quantity_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='priests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=150)),
                ('contact_number', models.IntegerField()),
            ],
        ),
    ]
