# Generated by Django 4.0.3 on 2022-08-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_priests'),
    ]

    operations = [
        migrations.CreateModel(
            name='ceremony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('available_priests', models.ManyToManyField(to='main_app.priests')),
            ],
        ),
    ]
