# Generated by Django 4.0.3 on 2022-08-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_travel'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
