# Generated by Django 4.1 on 2022-10-28 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_travel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color_quantity',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='main_app.pooja_products'),
        ),
    ]
