# Generated by Django 4.0.3 on 2022-10-29 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_alter_color_quantity_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color_quantity',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productt', to='main_app.pooja_products'),
        ),
    ]
