# Generated by Django 4.0.3 on 2022-10-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_alter_color_quantity_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color_quantity',
            name='photo',
            field=models.ImageField(null=True, upload_to='images', verbose_name='photo'),
        ),
    ]
