# Generated by Django 4.0.3 on 2023-04-06 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_alter_color_quantity_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color_quantity',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='main_app.pooja_products'),
        ),
    ]
