# Generated by Django 4.2 on 2023-07-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_alter_color_quantity_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved_address',
            name='name',
            field=models.CharField(default='Dummy name', max_length=50),
        ),
        migrations.AddField(
            model_name='saved_address',
            name='phone',
            field=models.CharField(default='1234567890', max_length=50),
        ),
    ]
