# Generated by Django 4.2 on 2023-08-26 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_color_quantity_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('reviews', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.color_quantity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.app_users')),
            ],
        ),
    ]
