# Generated by Django 4.2 on 2023-08-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_product_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_ratings',
            name='reviews',
            field=models.TextField(null=True),
        ),
    ]
