# Generated by Django 4.2 on 2023-09-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_alter_product_ratings_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved_address',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
