# Generated by Django 4.2 on 2023-10-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_saved_address_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='festivals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration', models.IntegerField()),
                ('duration_unit', models.CharField(choices=[('Hours', 'Hours'), ('Minutes', 'Minutes'), ('Days', 'Days')], default='Days', max_length=30)),
            ],
        ),
    ]
