# Generated by Django 4.2 on 2023-10-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_festivals'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceremony',
            name='festivals',
            field=models.ManyToManyField(to='main_app.festivals'),
        ),
    ]
