# Generated by Django 4.2 on 2023-10-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_ceremony_festivals'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceremony',
            name='date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='ceremony',
            name='duration',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ceremony',
            name='duration_unit',
            field=models.CharField(choices=[('Hours', 'Hours'), ('Minutes', 'Minutes'), ('Days', 'Days')], default='Days', max_length=30),
        ),
        migrations.AddField(
            model_name='ceremony',
            name='location',
            field=models.CharField(default='home', max_length=20),
        ),
        migrations.AddField(
            model_name='ceremony',
            name='materials_required',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='ceremony',
            name='procedure',
            field=models.TextField(default=' '),
        ),
    ]
