# Generated by Django 4.2 on 2023-10-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_ceremony_date_ceremony_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceremony',
            name='date_fixed',
            field=models.BooleanField(default=True),
        ),
    ]
