# Generated by Django 4.2 on 2023-10-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_ceremony_date_fixed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceremony',
            name='festivals',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='main_app.festivals'),
        ),
    ]
